### ISSUE TITLE
rails 5.2.3 ruby  2.5.1 添加gemfile无法启动服务

### ISSUE THREAD

**Issue by guojhq** [aliyun/openapi-core-ruby-sdk#18]
![image](https://user-images.githubusercontent.com/3446860/58377523-6f064200-7fb5-11e9-90fa-1dc978d8a87b.png)

**Comment by AxiosCros** [comment]
问题不像是出在 SDK 里的，错误信息可以再往上截一些吗？

**Comment by AxiosCros** [comment]
@guojhq 

你好。请问问题解决了吗？

长时间无回复的话，我就关掉这个问题了。

**Comment by guojhq** [comment]
哦  没有解决 ，就是SDK里 ，把他从Gemfile移除就OK了

**Comment by guojhq** [comment]
![image](https://user-images.githubusercontent.com/3446860/58600216-4bddda00-82b6-11e9-807f-61386a08c909.png)
![image](https://user-images.githubusercontent.com/3446860/58600228-57c99c00-82b6-11e9-8047-8e4de5dffac1.png)

**Comment by AxiosCros** [comment]
没有复现出你的问题。可以试着用以下命令配置中国区镜像, 更新 gem

```shell
# 使用中国区镜像
sudo gem sources --add https://gems.ruby-china.com/ --remove https://rubygems.org/
sudo bundle config mirror.https://rubygems.org https://gems.ruby-china.com

# 更新 gem
sudo gem update --system
```

**Comment by JacksonTian** [comment]
请升级到 0.0.9。

**Comment by guojhq** [comment]
好的 升级到0.0.9 OK了 谢谢
