### ISSUE TITLE
本项目是不支持ruby2.0及以下

### ISSUE THREAD

**Issue by VitalYoung** [aliyun/openapi-core-ruby-sdk#19]
项目lib/rpc_client.rb:24行定义函数时使用了ruby2.1的新功能`Required keyword arguments`

>In Ruby 2.1, required keyword arguments were added. In Ruby 2.0, keyword arguments must have default values.
https://thoughtbot.com/upcase/videos/ruby-keyword-arguments

麻烦在项目中标出不支持ruby2.0及以下版本的项目，以及在gem [aliyunsdkcore](https://rubygems.org/gems/aliyunsdkcore/versions/0.0.9)中增加ruby版本要求

**Comment by songshenzong** [comment]
> 项目lib/rpc_client.rb:24行定义函数时使用了ruby2.1的新功能`Required keyword arguments`
> 
> > In Ruby 2.1, required keyword arguments were added. In Ruby 2.0, keyword arguments must have default values.
> > https://thoughtbot.com/upcase/videos/ruby-keyword-arguments
> 
> 麻烦在项目中标出不支持ruby2.0及以下版本的项目，以及在gem [aliyunsdkcore](https://rubygems.org/gems/aliyunsdkcore/versions/0.0.9)中增加ruby版本要求

已收到，我们会轻快处理。

**Comment by JacksonTian** [comment]
已经在 gem 中限制了 ruby 版本。
