### ISSUE TITLE
是否包含 视频转码等媒体功能？

### ISSUE THREAD

**Issue by tianlu1677** [aliyun/openapi-core-ruby-sdk#9]

**Comment by AxiosCros** [comment]
这个sdk目前只是通用核心，可以根据它结合相关产品的接口文档进行特定产品接口的请求。

**Comment by JacksonTian** [comment]
@tianlu1677 亲 你可以参考 https://api.aliyun.com/#/?product=Ecs&api=DescribeAccessPoints&params={}&tab=DEMO&lang=RUBY ，并结合媒体处理的 API 文档自行构造参数进行调用。（不需要填写任何系统参数，仅业务参数即可）
